CREATE TABLE TASK (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
DESCRIPTION VARCHAR(250) NOT NULL );

INSERT INTO TASK (NAME, DESCRIPTION) VALUES('TASK1', 'PRIMEIRA TAREFA');
INSERT INTO TASK (NAME, DESCRIPTION) VALUES('TASK2', 'SEGUNDA TAREFA');
INSERT INTO TASK (NAME, DESCRIPTION) VALUES('TASK3', 'TERCEIRA TAREFA');